services:
  cd_platform.antispam:
       class: CD\PlatformBundle\Antispam\CDAntispam
       arguments:
            - "@mailer"
            - %locale%
            - 50
            
  cd_platform.email.application_mailer:
       class: CD\PlatformBundle\Email\ApplicationMailer
       arguments:
            - "@mailer"
            
  cd_platform.doctrine_listener_application_creation:
    class: CD\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
       - "@cd_platform.email.application_mailer"
    tags:
       - { name: doctrine.event_listener, event: postPersist }
       
  cd_platform.validator.noflood:                        # Le nom du service
    class: CD\PlatformBundle\Validator\NoFloodValidator # La classe du service, ici notre validateur déjà créé
    arguments:                                            # Les données qu'on injecte au service : la requête et l'EntityManager
      - "@request_stack"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: validator.constraint_validator, alias: cd_platform_flood }  # C'est avec l'alias qu'on retrouvera le service